name: PR Build

on:
  pull_request:
    # when using teardown: 'true', add default event types + closed event type
    #types: [opened, synchronize, reopened, closed]

#permissions:
#  pull-requests: write # allow surge-preview to create/update PR comments

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # environment: SurgePreviewPR
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Build JupyterBook
        run: |
          jb build book

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: book/_build/html

      # - name: Build and Publish to Surge
      #   id: preview_step
      #   uses: afc163/surge-preview@v1
      #   with:
      #     surge_token: ${{ secrets.SURGE_TOKEN }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     dist: book/_build/html
      #     teardown: true
      #     failOnError: true
      #     # website already built in previous step, just list existing folder
      #     build: echo 'skipping website build'

      # - name: Format preview url
      #   id: format_url
      #   run: |
      #     echo "url_text=:rocket: Preview deployed at https://${{ steps.preview_step.outputs.preview_url }}" >> $GITHUB_OUTPUT

      # - name: Get the preview_url
      #   run: echo "${{ steps.format_url.outputs.url_text }}"

      # - name: Generate summary
      #   run: |
      #     echo "#### ${{ steps.format_url.outputs.url_text }}" >> $GITHUB_STEP_SUMMARY
